### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [teddycomrad21/Homework-GRID#1]
проверьте размер шрифта
![image](https://user-images.githubusercontent.com/8464662/69670619-f9cb1500-109c-11ea-8449-6030d8047954.png)

фон не соответствует
![image](https://user-images.githubusercontent.com/8464662/69670649-07809a80-109d-11ea-8d37-dd7beab40b2a.png)
![image](https://user-images.githubusercontent.com/8464662/69670710-2bdc7700-109d-11ea-8e62-fb97faf6af49.png)

размер не соответствует
![image](https://user-images.githubusercontent.com/8464662/69670677-16ffe380-109d-11ea-89bd-b0a069b2ad51.png)

для мобильных устройств - вообще каша, даже проверять не стал.
уделите внимание тестированию своего кода абсолютно для всех перечисленных разрешений.

**Comment by Alecto** [comment]
высота секции не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/70119951-1c989300-1674-11ea-8b19-4da87456200f.png)

hover не соответствует
![image](https://user-images.githubusercontent.com/8464662/70120020-389c3480-1674-11ea-9a1c-ed87831ef6be.png)

цвет рамки не соответсвует
![image](https://user-images.githubusercontent.com/8464662/70120078-5cf81100-1674-11ea-93a9-2635ae1baaf1.png)
![image](https://user-images.githubusercontent.com/8464662/70120105-697c6980-1674-11ea-8a00-bdc2b2494da3.png)

**Comment by teddycomrad21** [comment]
Исправлено. Извиняюсь за количество ошибок.

https://github.com/teddycomrad21/Homework-GRID

https://teddycomrad21.github.io/Homework-GRID/

ср, 4 дек. 2019 г. в 09:01, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
не исправлено
![image](https://user-images.githubusercontent.com/8464662/70304606-fce7a300-180a-11ea-937f-992dac389d6a.png)

**Comment by teddycomrad21** [comment]
Исправлено

https://github.com/teddycomrad21/Homework-GRID

https://teddycomrad21.github.io/Homework-GRID/

пт, 6 дек. 2019 г. в 09:30, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
похоже, правильно.
работа принята.

сб, 7 груд. 2019 о 17:17 teddycomrad21 <notifications@github.com> пише:

**Comment by Alecto** [comment]
в письме нет заголовка.
Данил Черкашин?

сб, 7 груд. 2019 о 19:43 Андрей Фоменко <fomenkoandrey1978@gmail.com> пише:

**Comment by teddycomrad21** [comment]
да,   FrontEnd SkillUp. Черкашин Данил, сб/вс 11:00

сб, 7 дек. 2019 г. в 19:44, Andrey <notifications@github.com>:
